name: Publish Package

on:

  release:

    types: [created]

jobs:

  publish:

    runs-on: ubuntu-latest

    steps:

      - name: Set up Python

        uses: actions/setup-python@v2

        with:

          python-version: 3.x

      - name: Checkout code

        uses: actions/checkout@v2

      - name: Install dependencies

        run: |

          python -m pip install --upgrade pip setuptools wheel

          python -m pip install twine

      - name: Build distribution

        run: python setup.py sdist bdist_wheel

      - name: Publish to PyPI

        env:

          TWINE_USERNAME: ${{ secrets.TWINE_USERNAME }}

          TWINE_PASSWORD: ${{ secrets.TWINE_PASSWORD }}

        run: |

          python -m twine upload --skip-existing dist/* --repository-url https://upload.pypi.org/legacy/ --username ${{ secrets.TWINE_USERNAME }} --password ${{ secrets.TWINE_PASSWORD }}

